import os, time, pyautogui as auto

def switchInfo(x):
    auto.keyDown('shift')
    auto.scroll(x)
    auto.keyUp('shift')

def getEmail():
    auto.keyDown('ctrl')
    auto.click(1546,733)
    auto.keyUp('ctrl')

def runApp():
    auto.click(631,770, 2)
    auto.hotkey('ctrl', 'c')
    auto.hotkey('ctrl', 'tab')
    auto.click(928,266)
    auto.hotkey('ctrl', 'v')
    auto.hotkey('ctrl', 'tab')
    auto.moveTo(819,736)
    auto.dragTo(1343,732, 2, button='left')
    auto.hotkey('ctrl', 'c')
    auto.hotkey('ctrl', 'tab')
    auto.click(262,267)
    auto.hotkey('ctrl', 'v')
    auto.hotkey('ctrl', 'tab')
    auto.click(1527,734, 2)
    auto.hotkey('ctrl', 'c')
    auto.hotkey('ctrl', 'tab')
    auto.click(824,269)
    auto.hotkey('ctrl', 'v')
    auto.hotkey('ctrl', 'tab')
    switchInfo(-10000)
    getEmail()
    auto.click(371,15)
    auto.moveTo(634,52)
    auto.dragTo(234,52, 5, button='left')
    auto.hotkey('ctrl', 'c')
    auto.click(459,14)
    auto.hotkey('ctrl', 'tab')
    auto.click(553,268)
    auto.hotkey('ctrl', 'v')
    auto.hotkey('alt','tab')
    gender = input('Digite o gênero do Aluno(a):\n')
    year = input('Digite o ano de ingresso do Aluno(a):\n')
    auto.hotkey('alt','tab')
    auto.click(723,269)
    auto.write(gender)
    auto.click(1025,265)
    auto.write(year)
    auto.press('enter')
    auto.scroll(-25)
    auto.hotkey('ctrl', 'tab')
    switchInfo(10000)
    auto.click(631,770)
    auto.scroll(-155)

auto.hotkey('alt','tab')
auto.click(975,99)
auto.write('250')
auto.press('enter')
for i in range(0,4):
    runApp()



auto.mouseInfo()